version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-fpm
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - php

networks:
    app-network:
        driver: bridge
