services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-fpm
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - php

    db:
        image: postgres:17
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: postgre
            POSTGRES_USER: postgre
            POSTGRES_PASSWORD: 12345678
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    pgdata: